#Kafka的服务端列表，默认localhost
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.253.110:9092,192.168.253.111:9092
          zkNodes: 192.168.253.110:2181,192.168.253.111:2181
#Kafka服务端的默认端口，当brokers属性中没有配置端口信息时，就会使用这个默认端口，默认9092
#cloud.stream.kafka.binder.defaultBrokerPort=9092
#Kafka服务端连接的ZooKeeper节点列表，默认localhost
#spring.cloud.stream.kafka.binder.zkNodes=192.168.18.136:2181
#ZooKeeper节点的默认端口，当zkNodes属性中没有配置端口信息时，就会使用这个默认端口，默认2181
#spring.cloud.stream.kafka.binder.defaultZkPort=2181